name: ci
on:
  pull_request:
    paths:
      - 'scripts/**'
jobs:
  slow-job:
    runs-on: ubuntu-latest
    steps:
      - run: 'sleep 180'
  build:
    needs: [slow-job]
    runs-on: ubuntu-latest
    steps:
      - run: sleep 50
      - run: ' echo "Build succeeded" '
